docs(tutorial): awsim oss instruction
autowarefoundation/autoware-documentation pull request #213
Opened 2022-10-14 08:47 UTC by WJaworskiRobotec

Signed-off-by: Wojciech Jaworski <wojciech.jaworski@robotec.ai>

## Description

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-10-14 08:56 UTC, mitsudome-r requested changes

2022-10-14 08:56 UTC, mitsudome-r commented on docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
> +AWSIM is a default simulator for Autoware development and testing. To get started, please follow the official [instruction](https://tier4.github.io/AWSIM/GettingStarted/QuickStartDemo/) provided by T
```suggestion
AWSIM is a default simulator for Autoware development and testing. To get started, please follow the official [instruction](https://tier4.github.io/AWSIM/GettingStarted/QuickStartDemo/) provided by TIER IV.
```

2022-10-18 01:23 UTC, shmpwk commented
cc. @YoshinoriTsutake

2022-10-20 12:38 UTC, mitsudome-r approved these changes

2022-10-20 12:38 UTC, merged