feat: add console-logging doc
autowarefoundation/autoware-documentation pull request #216
Opened 2022-10-17 06:51 UTC by alanmengg

Signed-off-by: guiping meng <alan.meng@autocore.ai>

## Description

This pr add console-logging.md in autoware documentation.
related issue https://github.com/autowarefoundation/autoware-documentation/issues/212.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-10-17 08:21 UTC, shmpwk commented on docs/contributing/coding-guidelines/ros-nodes/console-logging.md
> +ROS2 logging is a powerful tool for understanding and debugging ros node.
```suggestion
ROS 2 logging is a powerful tool for understanding and debugging ros node.
```

2022-10-17 08:21 UTC, shmpwk commented on docs/contributing/coding-guidelines/ros-nodes/console-logging.md
> +The logging subsystem in ROS 2 delivers logging messages to a variety of targets, including console, disk and ROS2 network.
```suggestion
The logging subsystem in ROS 2 delivers logging messages to a variety of targets, including console, disk and ROS 2 network.
```

2022-10-19 01:36 UTC, shmpwk approved these changes

2022-10-20 05:10 UTC, kenji-miyake requested changes
@alanmengg Thank you for your proposal.
I'm sorry, but I wanted to write documents such as "Don't output too many logs the console." or "Wait for more than 5 seconds when you initialize the node and are waiting the data to be ready.".

So, can I propose a document and could you wait for that, please? I'm sorry for my late work.
Since your example and tips are pretty good, I'd like to reflect them to my proposal. If you want, I can merge them first.

2022-10-20 05:10 UTC, kenji-miyake commented on docs/contributing/coding-guidelines/ros-nodes/console-logging.md
> +- `SKIPFIRST` - output the given printf-style message all but the first time this line is hit
I feel this part can be delegated to the ROS 2 Documentation.
@alanmengg What is the reason that you want to write it here?

```suggestion
```

2022-10-20 05:10 UTC, kenji-miyake commented on docs/contributing/coding-guidelines/ros-nodes/console-logging.md
> +- {line_number} - The line number this was called from (may be empty)
It's already written in https://autowarefoundation.github.io/autoware-documentation/main/installation/additional-settings-for-developers/.

Could you update it if you feel it's unclear?

```suggestion
```

2022-10-20 10:00 UTC, alanmengg commented
> @alanmengg Thank you for your proposal. I'm sorry, but I wanted to write documents such as "Don't output too many logs the console." or "Wait for more than 5 seconds when you initialize the node and are waiting the data to be ready.".
> 
> So, can I propose a document and could you wait for that, please? I'm sorry for my late work. Since your example and tips are pretty good, I'd like to reflect them to my proposal. If you want, I can merge them first.

 thank u for your appreciation. of course, I can wait for the  proposal.

> @alanmengg Thank you for your proposal. I'm sorry, but I wanted to write documents such as "Don't output too many logs the console." or "Wait for more than 5 seconds when you initialize the node and are waiting the data to be ready.".
> 
> So, can I propose a document and could you wait for that, please? I'm sorry for my late work. Since your example and tips are pretty good, I'd like to reflect them to my proposal. If you want, I can merge them first.

 thank u for your appreciation. of course, I can wait for the  proposal.

2022-10-20 10:01 UTC, alanmengg commented
> @alanmengg Thank you for your proposal. I'm sorry, but I wanted to write documents such as "Don't output too many logs the console." or "Wait for more than 5 seconds when you initialize the node and are waiting the data to be ready.".
> 
> So, can I propose a document and could you wait for that, please? I'm sorry for my late work. Since your example and tips are pretty good, I'd like to reflect them to my proposal. If you want, I can merge them first.

 thank u for your appreciation. of course, I can wait for the  proposal.

2022-10-26 09:49 UTC, kenji-miyake commented
TODO(@kenji-miyake): Consider https://github.com/orgs/autowarefoundation/discussions/2824#discussioncomment-3967388 and https://github.com/autowarefoundation/autoware.universe/pull/2056. cc @xmfcx

2022-12-21 15:32 UTC, kenji-miyake commented
@alanmengg Hi, I'm so sorry to be late for my work. I had to do a lot of in-company work. :cry: 
I've submitted my proposal to this page #283. Could you review it?

Regarding your updates 406b3ea83a002ab17a0c75c7130465281254ff0b, I'll check it now.

2022-12-21 15:37 UTC, kenji-miyake commented
@alanmengg Oh, your updates look simple and nice! :smile: 
But I believe they are almost covered by my proposal #283 and it has a little more content. So, would it be possible for you to add your proposal to my proposal?

2022-12-26 04:06 UTC, alanmengg commented
> @alanmengg Oh, your updates look simple and nice! 😄 But I believe they are almost covered by my proposal #283 and it has a little more content. So, would it be possible for you to add your proposal to my proposal?

I‘ve read your  proposal, it's great, and it would be nice to combine them togther, but I don't know how to add my proposal to yours😢

2022-12-26 04:14 UTC, kenji-miyake commented
@alanmengg Thank you for your feedback.
You can add review comments to https://github.com/autowarefoundation/autoware-documentation/pull/283, or update this PR after https://github.com/autowarefoundation/autoware-documentation/pull/283 is merged.
Any way you prefer is okay for me.

2022-12-26 09:10 UTC, alanmengg commented
> @alanmengg Thank you for your feedback. You can add review comments to #283, or update this PR after #283 is merged. Any way you prefer is okay for me.
I directly add review comments in #283, but sincerely there's not much to add after i review it thoroughly. Thank u for the great content!👍 Should I close this pr?

2022-12-26 09:28 UTC, kenji-miyake commented
@alanmengg Yes, if you feel #283 covers all content, you can close this.

2022-12-26 10:09 UTC, alanmengg commented
As #283 covers mostly and more content than this pr. It is closed now

2022-12-26 10:09 UTC, closed without merging