docs: add advanced usage of colcon
autowarefoundation/autoware-documentation pull request #27
Opened 2022-02-14 14:24 UTC by kenji-miyake

2022-02-15 13:46 UTC, xmfcx commented on docs/how-to-guides/advanced-usage-of-colcon.md
> +It is recommended to use it to save your time if there are no particular reasons.
```suggestion
It is recommended to use it to save your time unless you have a specific reason not to do so.
```

2022-02-15 13:47 UTC, kenji-miyake commented on docs/how-to-guides/advanced-usage-of-colcon.md
> +It is recommended to use it to save your time if there are no particular reasons.
Thank you!

2022-02-16 15:05 UTC, kenji-miyake commented on docs/how-to-guides/advanced-usage-of-colcon.md
> +## Using Ccache
@xmfcx FYI: Added to the dictionary by this PR.
https://github.com/tier4/autoware-spell-check-dict/pull/224

2022-02-16 15:06 UTC, kenji-miyake commented on docs/how-to-guides/advanced-usage-of-colcon.md
> +## Using Ccache
And the spell-check CI has passed if I run it again.
https://github.com/autowarefoundation/autoware-documentation/runs/5218266236?check_suite_focus=true

2022-02-16 15:14 UTC, kenji-miyake commented on docs/how-to-guides/advanced-usage-of-colcon.md
> +## Using Ccache
By the way, if you want to see files without being disturbed by some comments, you can try either:

1. Click the `View file` button
![image](https://user-images.githubusercontent.com/31987104/154294797-ec1efcb1-a560-447c-91d6-c4cc7eb2d019.png)

2. Use the rich view
![image](https://user-images.githubusercontent.com/31987104/154294726-ae6e9b94-bc5c-4b3b-b481-47aa7d931323.png)

2022-02-18 13:10 UTC, xmfcx requested changes

2022-02-18 13:10 UTC, xmfcx commented on docs/how-to-guides/index.md
>  - Write an Autoware package
```suggestion
- Create an Autoware package
```

2022-02-18 14:01 UTC, xmfcx submitted a review, later dismissed

2022-02-18 14:09 UTC, kenji-miyake commented
I'll merge this after #18.

2022-03-11 10:36 UTC, kenji-miyake commented
Just rebased.

2022-03-11 10:36 UTC, merged