docs: add apt update/upgrade to workspace install/update instructions
autowarefoundation/autoware-documentation pull request #615
Opened 2024-09-19 06:04 UTC by mojomex

## Description

Added missing instructions to the following guides:
* Docker update
* Source install
* Source update

Specifically, `sudo apt update && sudo apt upgrade` were missing: `rosdep update` and `rosdep install` will not upgrade previously installed `ros-$ROS_DISTRO-*` packages (even when Autoware is expected to be built with newer versions), which often results in unexpected Autoware build failures.
From my experience in the last two weeks, following the instructions perfectly on a clean Autoware repo succeeded one out of five times mainly due to this issue.

I also added comments that for moved/removed dependencies in the `repos` files, `vcstool` will not sync correctly and result in duplicate or wrongly remaining packages, in which case the `src` directory has to be deleted and re-pulled.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-09-19 12:22 UTC, xmfcx commented
This workflow works on `pull_request_target:` so it can't be tested like this :(

I will just go ahead and merge the other PR.

2024-09-19 12:29 UTC, xmfcx commented on docs/installation/autoware/docker-installation.md
> +> rm -rf src
```suggestion
> rm -rf src/*
```

Otherwise you need to recreate the `src` folder to do the next line.

2024-09-19 12:31 UTC, xmfcx commented on docs/installation/autoware/source-installation.md
> +   rm -rf src
```suggestion
   rm -rf src/*
```

Similar to the previous comment.

2024-09-19 12:34 UTC, xmfcx requested changes
Thanks @mojomex for improving the documentation!

Fixed the deploy-docs workflow and added 2 comments to the PR.

2024-09-21 16:06 UTC, mojomex commented
@xmfcx Thanks for the suggestions, I've committed them :raised_hands:

2024-09-23 07:51 UTC, xmfcx approved these changes
Thanks!

2024-09-23 07:51 UTC, merged